### ISSUE TITLE
Why isn't this project called "nbexecute"?

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbclient#14]
I was wondering what `nbclient` is supposed to do except executing ... and I asked there: https://github.com/jupyter/nbclient/issues/4#issuecomment-579499964

This was answered by @MSeal in https://github.com/jupyter/nbclient/issues/4#issuecomment-581790592:

> For now the intention is to have a very narrow scoped notebook executor that has few dependencies, like jupyter_client does for interacting with kernels. This library doesn't handle output IO and does one thing well. It'll likely get an async execution pattern, but beyond that I don't see major responsibilities being added to the core the library for now.

So if it is only ever supposed to "execute", why call it by a totally un-intuitive and confusing name?

**Comment by choldgraf** [comment]
I think it's reasonable to bring up the name of the project as a topic for discussion. I agree that `nbexecute` would be more intuitive for me, but I am not sure if there were other reasons that `nbclient` was chosen as the name. Either way it is not something I feel super strongly about

---

That said, please use a more constructive tone when you're engaging with this community - calling something confusing and un-intuitive is an opinion, not a factual statement, and blanket statements like this carry with it a negative connotation that may not lead to constructive discussion. For example, another way to say the same thing is "The name `nbclient` feels unintuitive to me, and may be to others". (I won't mention it there, but the same thing applies to #15). Please keep comments neutral-to-positive, and constructive.

**Comment by MSeal** [comment]
My original idea was to name this nbexecute. I shopped the naming around with a number of the jupyter core devs and nbclient was the name most voted for. The parallel to jupyter_client for responsibilities was what resonated for folks.

Here's the list of names I ended up sending to folks:

- nbexec
- nbexecute
- nbproc  
- nbclient (plays ontop of the jupyter_client naming theme)
- nbscribe
- scribbles (bottom of the barrel)

I'm in a similar line of thought as @choldgraf , but given the naming was already picked among a few core devs I'd prefer to not change it unless it was deemed as problematic or many people thought it was a bad fit.

But you know... "There are only two hard things in Computer Science: cache invalidation and naming things" - Phil Karlton

**Comment by choldgraf** [comment]
One thought here - we could include a short description of the reasoning behind the name in the docs. At the least it could help users remember the name...is there a public place where the `nbclient` naming conversation happened?

**Comment by MSeal** [comment]
There are several disconnected threads across a few projects, some threads in a few open chat systems, and a few emails to jupyter core devs (as I just wanted a smaller group to make a decision). Probably a little hard to collect all those for user visibility, but I really like the idea of documenting the name choice in the readthedocs

**Comment by mgeier** [comment]
Thanks for all the answers!

I think I know now what's the problem: y'all want to do two different things in one project:

1. have an object-oriented wrapper for handling kernels and communicating with them (the classes from https://jupyter-client.readthedocs.io/en/stable/api/client.html are probably too low-level?)
2. use that abstraction to execute a notebook

The first thing should really be independent of notebooks. I guess this functionality should either be added to the `jupyter_client` project or moved into a separate project (whose name doesn't contain `nb`).

Once such a class exists, implementing the `nbexecute` project should only consist of two main functions:

* given the metadata section of a notebook, start a kernel
* given a notebook cell, execute it (updating the current state) and return the results

The `execute()` convenience function would call the first function and then iterate over all cells and call the second function for each cell.

Separating those two concerns would also make the naming easier: The first component would either be part of `jupyter_client` or would get a similar name like `simple_jupyter_client`, while the second component could simply be called `nbexecute`.

**Comment by MSeal** [comment]
If I were to re-organize and rewrite the stack of jupyter libraries all at once, I would probably prefer the proposed pattern @mgeier , along with removing a bunch of the boilerplate code like traitlets and odd duplicate configuration like the various error handling flags.

To do this cleanly though I think you need to rework the responsibilities and contract in jupyter client, as it doesn't track enough kernel execution state that's needed as display objects or widgets mutate (also the state isn't even specific to the kernel, it's specific to a particular notebook running in the kernel because of how those libraries above were developed). Thus you need some ugly state trackers for a few abstrations that should be transparent to library uses, hence why today this library has an object holding state during a single notebook execution which doesn't share with other notebook executions. Even when with a refactor now jupyter_client would leak memory for older notebook states as you executed future notebooks, or you'd have to pass those state holders across cell execution calls as arguments that clutter the interface. No silver bullet solution to making it cleaner imho. I'm always for simpler interfaces where possible as these conversations reveal them.

I might step back from digging deep into nbclient topics for a bit, outside of bugs, and get some of the other major releases finished that have been waiting for months to be finished.

**Comment by mgeier** [comment]
OK, I understand that a re-write of the whole ecosystem isn't feasible at the moment ...

But adding a known-to-be-flawed public API now just makes the problem worse!

Even if we cannot improve the API-situation of the whole Jupyter ecosystem at once, we can at least try to not make it worse, shall we?

I think the best course of action right now would be to add the `NotebookClient` class (and the whole `client` sub-module) as a hidden implementation detail.
It should be enough to provide the stand-alone function `execute()` as only public API for now, shouldn't it?

This way, the implementation can be refactored at a later time and once a good API is found, it can be made public without breaking anything.

**Comment by MSeal** [comment]
I'm going to close this for now. The name has been sticking well enough and downstream developers have been building against the interface successfully.
